version: '3.8'

services:
  texter.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5005
      - ASPNETCORE_HTTPS_PORTS=5006
      - DOTNET_URLS=https://+:5006
    ports:
      - "5005"
      - "5006"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro